### ISSUE TITLE
Unsupported SQL Server Prior to SQL Server 2012 - OFFSET-FETCH clause problem

### ISSUE THREAD

**Issue by endrihacker** [gpeipman/DotNetPaging#3]
I have tried to connect to a SQL Server 2018 R2 instance but it causes the following error:

> SqlException: Incorrect syntax near 'OFFSET'.
 Invalid usage of the option NEXT in the FETCH statement.

I used DotNetPaging.AspNetCore project to test it.

Is it possible to make some changes to use SQL Server 2018 R2 instead of upgrading to SQL Server 2012 or later?

**Comment by gpeipman** [comment]
Merged to latest version
